# Generated by Django 3.0 on 2019-12-07 22:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spauser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spauser',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
